### ISSUE TITLE
More API commands available?

### ISSUE THREAD

**Issue by Ron168** [jessevl/homeassistant-greenchoice#11]
Hi Jesse,

The plugin is working fine, thanks for that!
Do you happen to know where to find any API documentation?
I would like to extend your plugin with the "Tarieven" (tariffs), so I can see how much Euro is "consumed" rather than kWh.
The only thing missing is the right URL.

Thanks in advance.

Best,
Ron

**Comment by jessevl** [comment]
Unfortunately the API is undocumented and the endpoints in this project are the only ones I have been able to find. If somebody has more info that would be great but I've not heard of anyone thus far. You could try sniffing traffic from the phone app.

Closing this one for now.

**Comment by victorclaessen** [comment]
I may have some more information:

With [Diggy](https://github.com/s0md3v/Diggy) I unpacked the APK. That only gave me some servers, but not the URL endpoints. But if you go inside the folder where Diggy unpacked the APK, then with this command ```grep -R "api/v[12]" .``` you can find many api endpoints. Then you look inside the corresponding .smali file, and there you can find which parameters to give in the api call.

for instance:
- https://app.greenchoice.nl/api/v1/features/beschikbaar?overeenkomstid=
- https://app.greenchoice.nl/api/v1/WindVanger/Details?overeenkomstid=

I hope that is enough to get you started on extending the plugin.

Full output of the grep command attached.
[api.txt](https://github.com/jessevl/homeassistant-greenchoice/files/6670445/api.txt)

**Comment by Ron168** [comment]
This can be used:
https://app.greenchoice.nl/api/v2/verbruik/gettarieven?overeenkomstid=

However, I've no clue what the resulting numbers mean:
{
    "TariefElektra": 0.05465,
    "TariefGas": 0,
    "TariefREB10k": 0.09428,
    "TariefREB5k": 0
}

TariefREB10k corresponds with "Energiebelasting" but the actually tariffs I cannot find.
Any clues?

**Comment by mcwieger** [comment]
Would love to get Windvanger info in HA and add it to the new Energy dashboard, to get a full overview of my energy usage.
