### ISSUE TITLE
Screenshot Postman

### ISSUE THREAD

**Issue by filmgarage** [jessevl/homeassistant-greenchoice#12]
Would you be so kind to add screenshots to the readme section how to input the POST request?
I am not able to figure that out and I would love to use this component.

**Comment by filmgarage** [comment]
I managed to get the contract_id through a curl command, that turned out to be easier for me. Would be nice if this info is included in the readme... Thanks for a nice new component in my HA setup!!!

**Comment by jessevl** [comment]
Good to hear! Could you add the Curl command in the readme and do a PR?

**Comment by filmgarage** [comment]
I believe I followed the commands described by @eelcohn in #2

**Comment by filmgarage** [comment]
https://github.com/jessevl/homeassistant-greenchoice/issues/2#issuecomment-629239304
