### ISSUE TITLE
Date range only 1 day?

### ISSUE THREAD

**Issue by ChillXXL** [jessevl/homeassistant-greenchoice#13]
I received data with the GET "https://app.greenchoice.nl/api/v2/meterstanden/getstanden?".
I did only receive 1 day. Is this common? Is there also a way to extend the data range?

**Comment by dutchcandy** [comment]
I think that you only receive the "actual" data. Just the same idea as you would look at your meter and see the data over there.
It is not historical just like no history is found at the display of your meter.

**Comment by jessevl** [comment]
This is correct. Unfortunately I do not have documentation for other parts of the API that might give us history.
