### ISSUE TITLE
Cannot find sensor

### ISSUE THREAD

**Issue by DavyRoswinkel** [jessevl/homeassistant-greenchoice#18]
I added all info in my sensor.yaml ( config include !sensor.yaml)
- platform: greenchoice
    name: meterstanden
    password: !secret greenchoicepass
    username: !secret greenchoiceuser
    overeenkomst_id: !secret greenchoicecontract
    
Of cource also installed the HACS Greenchoice.

I found my contract id with the curl instructions.
But now I cannot find a sensor anywhere on HA.

**Comment by dutchcandy** [comment]
@DavyRoswinkel  I seem to have the same issue. How did you solve this?

**Comment by DavyRoswinkel** [comment]
@dutchcandy 
I was looking for the wrong sensor, something with greenchoice.
Sensor names are:
sensor.currentenergyday
sensor.currentenergynight
sensor.currentenergytotal
sensor.currentgas

Hope this solves your problem also.

**Comment by dutchcandy** [comment]
sure does ! thanks

**Comment by DavyRoswinkel** [comment]
@dutchcandy 
You're welcome!
