### ISSUE TITLE
No sensor created?? How can I use the data retrieved?

### ISSUE THREAD

**Issue by dutchcandy** [jessevl/homeassistant-greenchoice#19]
I succesfully installed the custom component. 
When looking in the debug logfiles of HA, I also see the data is retrieved from Greenchoice. 

However, I can not find en entity in HA with attributes of something like that. 
How exactly can I use the data retrieved bij the Greenchoice Integration?

**Comment by dutchcandy** [comment]
Never mind, found it :-)

**Comment by Sander-Toonen** [comment]
Would you like to share your knowledge? I'm in the same situation.

**Comment by jessevl** [comment]
@Sander-Toonen See #18
