### ISSUE TITLE
Gasmeter readings parsed incorrect

### ISSUE THREAD

**Issue by HumanPrinter** [jessevl/homeassistant-greenchoice#20]
I thing the parsing of the API output is not correct. For the gas meter index 1 of the output is read. However, looking at the output I get when invoking the API manually, the gasmeter readings are at index 2. I think the code should look at the Product-field to determine the correct JSON-object for the meter readouts.
I also don't seem to get any 'Delivered' measurements but since I can't find any documentation about the Greenchoice API I'm not sure what the reason for this could be.

I pasted the output I got in the hope that it would help with the development.

    [  
        {  
            "MeterstandenOutput": [  
                {
                    "MinNieuweStand": 0,
                    "MaxNieuweStand": 0,
                    "Hoog": 2484,
                    "Laag": 2905,
                    "Product": 1
                }
            ],
            "DatumInvoer": "2020-12-30T00:00:00"
        },
        {
            "MeterstandenOutput": [
                {
                    "MinNieuweStand": 0,
                    "MaxNieuweStand": 0,
                    "Hoog": 0,
                    "Laag": 0,
                    "Product": 2
                }
            ],
            "DatumInvoer": "2020-12-30T00:00:00"
        },
        {
            "MeterstandenOutput": [
                {
                    "MinNieuweStand": 0,
                    "MaxNieuweStand": 0,
                    "Hoog": 2931,
                    "Laag": 0,
                    "Product": 3
                }
            ],
            "DatumInvoer": "2020-12-30T00:00:00"
        }
    ]

**Comment by jessevl** [comment]
This relates to #7 and indeed should be fixed. I'll look at this when I can find the time, or if someone else feels like they can fix this I'm open to PRs.

**Comment by jessevl** [comment]
#22
