### ISSUE TITLE
What is the clientID to be used for GreenChoice API?

### ISSUE THREAD

**Issue by maikeru010** [jessevl/homeassistant-greenchoice#21]
Hi, than you for creating this Custom sensor.

I try to retreive my access token but when I enter the command in POSTman, I get the following result:

{
    "error": "invalid_clientId",
    "error_description": "ClientId should be sent."
}

I've tried different entries for ClientID, like my e-mail address, customer number and even just my name, everythime with the same error.

Do I need to add my ClientID between special characters due to the fact it's an e-mailaddress? Or does it have something to do with my password (there are special characters in it).

Can you please help?

Thanks!
Michael

**Comment by jessevl** [comment]
Hi Michael, the client_id and client_secret can be taken directly from the sample in the documentation (they are the same for all users).

**Comment by maikeru010** [comment]
Hi Jesse, Thank you. I thought clientid was miy ID. I managed to get it to work using some more explanation about POSTman. 

* Open POSTMAN
* Click on "import" tab on the upper left side.
* Select the Raw Text option and paste your cURL command.
* Hit import and you will have the command in your Postman builder!
* Click Send to post the command

Thanks very much
