### ISSUE TITLE
How to test

### ISSUE THREAD

**Issue by ericschalker** [jessevl/homeassistant-greenchoice#3]
Hi Jesse,

I have installed this plugin. And I received a id.
Everything is ok, but how can i implement or test this?

I can't find any entitie with 'meterstand' of with 'greenchoice'.

**Comment by jessevl** [comment]
The entity names are (sensor.) "currentGas", "currentEnergyDay", "currentEnergyNight", and "currentEnergyTotal".

Hope this helps.

**Comment by ericschalker** [comment]
Hi Jesse,

It likes it works!
I have 'verbruik'. So it seems to work. Nice!

Is it possible to see a history like solaredge?

![afbeelding](https://user-images.githubusercontent.com/48595631/79052972-4bce9a80-7c3a-11ea-85d7-915225a327e0.png)

**Comment by jessevl** [comment]
You can utilize the [utility meter](https://www.home-assistant.io/integrations/utility_meter/) component. although it is a little unreliable because the values from the api are not updated on regular intervals.
